name: Deploy to Azure Static Web Apps

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # For pure static sites, set both locations to "/"
      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          # If your SWA was created via the Azure Portal with GitHub auth,
          # Azure usually injects a secret named like AZURE_STATIC_WEB_APPS_API_TOKEN_<HASH>.
          # If you created your own secret, use that one instead.
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""                # no API
          app_artifact_location: "/"      